version: '3'

services:
  lb:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
  app:
    image: prometherion/php7-nginx:1.1.3
    volumes:
      - ./app:/var/www
