version: '3'

services:
  app:
    user: root
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      #
      # Redis as Cache driver
      #
      CACHE_DRIVER: redis
      REDIS_HOST: cache
      #
      # MySQL as RDMS
      #
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravelday
      DB_USERNAME: user
      DB_PASSWORD: password
  
  database:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: laravelday
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  
  cache:
    image: redis