FROM php:5.6-fpm

WORKDIR /var/www

ADD ./composer.json ./composer.json

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
	php composer-setup.php \
	php -r "unlink('composer-setup.php');" \
	composer install